Card(
    
    abilities=None, 
    artist='Atsushi Furusawa', 
    ancientTrait=None, 
    attacks=
        [Attack(
            name='Vee-Search', 
            cost=['Colorless'], 
            convertedEnergyCost=1,
            damage='', 
            text='Search your deck for up to 3 Pokémon V, reveal them, and put them into your hand. Then, shuffle your deck.'), 
        Attack(
            name='Stampede', 
            cost=['Colorless', 'Colorless'], 
            convertedEnergyCost=2, 
            damage='20', 
            text='')], 
    cardmarket=
        Cardmarket(url='https://prices.pokemontcg.io/cardmarket/swsh7-125', 
        updatedAt='2024/10/25', 
        prices=CardmarketPrices(
            averageSellPrice=0.07, 
            lowPrice=0.02, 
            trendPrice=0.06, 
            germanProLow=0.0, 
            suggestedPrice=0.0, 
            reverseHoloSell=0.28, 
            reverseHoloLow=0.02, 
            reverseHoloTrend=0.39, 
            lowPriceExPlus=0.02,
            avg1=0.08, 
            avg7=0.08, 
            avg30=0.07, 
            reverseHoloAvg1=0.5, 
            reverseHoloAvg7=0.4, 
            reverseHoloAvg30=0.29)), 
    convertedRetreatCost=1, 
    evolvesFrom=None, 
    flavorText='Thanks to its unstable genetic makeup, this special Pokémon conceals many different possible evolutions.',
    hp='70', id='swsh7-125', 
    images=CardImage(
        small='https://images.pokemontcg.io/swsh7/125.png', 
        large='https://images.pokemontcg.io/swsh7/125_hires.png'), 
    legalities=Legality(
        unlimited='Legal', 
        expanded='Legal', 
        standard='Legal'), 
    regulationMark='E', 
    name='Eevee', 
    nationalPokedexNumbers=[133], 
    number='125', 
    rarity='Common', 
    resistances=None, 
    retreatCost=['Colorless'], 
    rules=None, 
    set=Set(
        id='swsh7', 
        images=SetImage(
            symbol='https://images.pokemontcg.io/swsh7/symbol.png', 
            logo='https://images.pokemontcg.io/swsh7/logo.png'), 
            legalities=Legality(
                unlimited='Legal', 
                expanded='Legal', 
                standard='Legal'), 
        name='Evolving Skies', 
        printedTotal=203, 
        ptcgoCode='EVS', 
        releaseDate='2021/08/27', 
        series='Sword & Shield', 
        total=237, 
        updatedAt='2021/08/27 10:17:00'), 
    subtypes=['Basic'], 
    supertype='Pokémon', 
    tcgplayer=TCGPlayer(
        url='https://prices.pokemontcg.io/tcgplayer/swsh7-125', 
        updatedAt='2024/10/25', 
        prices=TCGPrices(
            normal=TCGPrice(
                low=0.01, 
                mid=0.1, 
                high=4.39, 
                market=0.08, 
                directLow=0.02), 
            holofoil=None, 
            reverseHolofoil=TCGPrice(
                low=0.06, 
                mid=0.25, 
                high=89.0, 
                market=0.19, 
                directLow=0.15), 
            firstEditionHolofoil=None, 
            firstEditionNormal=None)), 
    types=['Colorless'], 
    weaknesses=[Weakness(
        type='Fighting', 
        value='×2')]
)